name: rolla_zadatak
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_route: ^6.0.3
  dio: ^5.4.2+1
  flutter_bloc: ^8.1.1
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.20
  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator: ^6.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  another_flushbar: ^1.12.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
